name: pipeline

on:
  push:
    branches-ignore:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup zig
        uses: mlugg/setup-zig@v2

      - name: build
        run: zig build

      - name: format
        run: zig fmt --check .

      - name: test
        run: zig build test --summary all
  build:
    needs: test
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup zig
        uses: mlugg/setup-zig@v2

      - name: build
        run: zig build -Dtarget=x86_64-windows -Doptimize=ReleaseSafe

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gta-ppl
          path: ./zig-out/bin/gta-ppl.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: gta-ppl
          merge-multiple: true

      - name: generate checksums
        run: |
          cd ./artifacts
          sha256sum gta-ppl.exe > checksum.txt

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/gta-ppl.exe
            ./artifacts/checksum.txt
            LICENSE
